---

- include_vars: raspberry_pi.yml
  when: ansible_lsb.id == 'Raspbian'

- include_vars: debian_64.yml
  when:
    - ansible_os_family == 'Debian'
    - ansible_userspace_architecture == 'x86_64'

- include_tasks: install_binary.yml
- include_tasks: monit_autostart.yml
