---

- name: Create Autostart Script
  template:
    src: monit.service.j2
    dest: /lib/systemd/system/monit.service
    owner: root
    group: "{{ monit_group }}"
    mode: 0644
  when: ansible_os_family == "Debian"
  become: true
  register: _debian_autostart_script

- name: Register Monit's Autostart Script
  systemd:
    state: started
    name: monit.service
    enabled: yes
    daemon_reload: yes
  when: _debian_autostart_script|changed
  failed_when: false
