---

- name: Debian | Restart Monit
  service:
    name: monit
    enabled: yes
    state: restarted

- name: macOS | Restart Monit
  shell: '/usr/local/bin/lunchy restart -w com.tildeslash.monit'
  become: true
